// Copyright (c) 1981-86 Robert A. Koeneke
// Copyright (c) 1987-94 James E. Wilson
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Player character data

use crate::character::{Background, Class, Race};
use crate::config;
use crate::player::{CLASS_MAX_LEVEL_ADJUST, PLAYER_MAX_BACKGROUNDS, PLAYER_MAX_CLASSES, PLAYER_MAX_LEVEL, PLAYER_MAX_RACES};
use crate::spells_data::Spell;

// Class rank titles for different levels
pub static CLASS_RANK_TITLES: [[&str; PLAYER_MAX_LEVEL]; PLAYER_MAX_CLASSES] = [
    // Warrior
    [
        "Rookie", "Private", "Soldier", "Mercenary",
        "Veteran(1st)", "Veteran(2nd)", "Veteran(3rd)", "Warrior(1st)",
        "Warrior(2nd)", "Warrior(3rd)", "Warrior(4th)", "Swordsman-1",
        "Swordsman-2", "Swordsman-3", "Hero", "Swashbuckler",
        "Myrmidon", "Champion-1", "Champion-2", "Champion-3",
        "Superhero", "Knight", "Superior Knt", "Gallant Knt",
        "Knt Errant", "Guardian Knt", "Baron", "Duke",
        "Lord (1st)", "Lord (2nd)", "Lord (3rd)", "Lord (4th)",
        "Lord (5th)", "Lord (6th)", "Lord (7th)", "Lord (8th)",
        "Lord (9th)", "Lord Gallant", "Lord Keeper", "Lord Noble",
    ],
    // Mage
    [
        "Novice", "Apprentice", "Trickster-1", "Trickster-2",
        "Trickster-3", "Cabalist-1", "Cabalist-2", "Cabalist-3",
        "Visionist", "Phantasmist", "Shadowist", "Spellbinder",
        "Illusionist", "Evoker (1st)", "Evoker (2nd)", "Evoker (3rd)",
        "Evoker (4th)", "Conjurer", "Theurgist", "Thaumaturge",
        "Magician", "Enchanter", "Warlock", "Sorcerer",
        "Necromancer", "Mage (1st)", "Mage (2nd)", "Mage (3rd)",
        "Mage (4th)", "Mage (5th)", "Wizard (1st)", "Wizard (2nd)",
        "Wizard (3rd)", "Wizard (4th)", "Wizard (5th)", "Wizard (6th)",
        "Wizard (7th)", "Wizard (8th)", "Wizard (9th)", "Wizard Lord",
    ],
    // Priests
    [
        "Believer", "Acolyte(1st)", "Acolyte(2nd)", "Acolyte(3rd)",
        "Adept (1st)", "Adept (2nd)", "Adept (3rd)", "Priest (1st)",
        "Priest (2nd)", "Priest (3rd)", "Priest (4th)", "Priest (5th)",
        "Priest (6th)", "Priest (7th)", "Priest (8th)", "Priest (9th)",
        "Curate (1st)", "Curate (2nd)", "Curate (3rd)", "Curate (4th)",
        "Curate (5th)", "Curate (6th)", "Curate (7th)", "Curate (8th)",
        "Curate (9th)", "Canon (1st)", "Canon (2nd)", "Canon (3rd)",
        "Canon (4th)", "Canon (5th)", "Low Lama", "Lama-1",
        "Lama-2", "Lama-3", "High Lama", "Great Lama",
        "Patriarch", "High Priest", "Great Priest", "Noble Priest",
    ],
    // Rogues
    [
        "Vagabond", "Footpad", "Cutpurse", "Robber",
        "Burglar", "Filcher", "Sharper", "Magsman",
        "Common Rogue", "Rogue (1st)", "Rogue (2nd)", "Rogue (3rd)",
        "Rogue (4th)", "Rogue (5th)", "Rogue (6th)", "Rogue (7th)",
        "Rogue (8th)", "Rogue (9th)", "Master Rogue", "Expert Rogue",
        "Senior Rogue", "Chief Rogue", "Prime Rogue", "Low Thief",
        "Thief (1st)", "Thief (2nd)", "Thief (3rd)", "Thief (4th)",
        "Thief (5th)", "Thief (6th)", "Thief (7th)", "Thief (8th)",
        "Thief (9th)", "High Thief", "Master Thief", "Executioner",
        "Low Assassin", "Assassin", "High Assassin", "Guildsmaster",
    ],
    // Rangers
    [
        "Runner (1st)", "Runner (2nd)", "Runner (3rd)", "Strider (1st)",
        "Strider (2nd)", "Strider (3rd)", "Scout (1st)", "Scout (2nd)",
        "Scout (3rd)", "Scout (4th)", "Scout (5th)", "Courser (1st)",
        "Courser (2nd)", "Courser (3rd)", "Courser (4th)", "Courser (5th)",
        "Tracker (1st)", "Tracker (2nd)", "Tracker (3rd)", "Tracker (4th)",
        "Tracker (5th)", "Tracker (6th)", "Tracker (7th)", "Tracker (8th)",
        "Tracker (9th)", "Guide (1st)", "Guide (2nd)", "Guide (3rd)",
        "Guide (4th)", "Guide (5th)", "Guide (6th)", "Guide (7th)",
        "Guide (8th)", "Guide (9th)", "Pathfinder-1", "Pathfinder-2",
        "Pathfinder-3", "Ranger", "High Ranger", "Ranger Lord",
    ],
    // Paladins
    [
        "Gallant", "Keeper (1st)", "Keeper (2nd)", "Keeper (3rd)",
        "Keeper (4th)", "Keeper (5th)", "Keeper (6th)", "Keeper (7th)",
        "Keeper (8th)", "Keeper (9th)", "Protector-1", "Protector-2",
        "Protector-3", "Protector-4", "Protector-5", "Protector-6",
        "Protector-7", "Protector-8", "Defender-1", "Defender-2",
        "Defender-3", "Defender-4", "Defender-5", "Defender-6",
        "Defender-7", "Defender-8", "Warder (1st)", "Warder (2nd)",
        "Warder (3rd)", "Warder (4th)", "Warder (5th)", "Warder (6th)",
        "Warder (7th)", "Warder (8th)", "Warder (9th)", "Guardian",
        "Chevalier", "Justiciar", "Paladin", "High Lord",
    ],
];

// Race, STR, INT, WIS, DEX, CON, CHR,
//   ages, heights, and weights (male then female)
// Racial Bases for:
//   dis, chance_in_search, stealth_factor, fos, bth, bth_with_bows, saving_throw_base,
//   hit_die, infra, exp base, choice-classes
pub static CHARACTER_RACES: [Race; PLAYER_MAX_RACES] = [
    Race {
        name: "Human",
        str_adjustment: 0,
        int_adjustment: 0,
        wis_adjustment: 0,
        dex_adjustment: 0,
        con_adjustment: 0,
        chr_adjustment: 0,
        base_age: 14,
        max_age: 6,
        male_height_base: 72,
        male_height_mod: 6,
        male_weight_base: 180,
        male_weight_mod: 25,
        female_height_base: 66,
        female_height_mod: 4,
        female_weight_base: 150,
        female_weight_mod: 20,
        disarm_chance_base: 0,
        search_chance_base: 0,
        stealth: 0,
        fos: 0,
        base_to_hit: 0,
        base_to_hit_bows: 0,
        saving_throw_base: 0,
        hit_points_base: 10,
        infra_vision: 0,
        exp_factor_base: 100,
        classes_bit_field: 0x3F,
    },
    Race {
        name: "Half-Elf",
        str_adjustment: -1,
        int_adjustment: 1,
        wis_adjustment: 0,
        dex_adjustment: 1,
        con_adjustment: -1,
        chr_adjustment: 1,
        base_age: 24,
        max_age: 16,
        male_height_base: 66,
        male_height_mod: 6,
        male_weight_base: 130,
        male_weight_mod: 15,
        female_height_base: 62,
        female_height_mod: 6,
        female_weight_base: 100,
        female_weight_mod: 10,
        disarm_chance_base: 2,
        search_chance_base: 6,
        stealth: 1,
        fos: -1,
        base_to_hit: -1,
        base_to_hit_bows: 5,
        saving_throw_base: 3,
        hit_points_base: 9,
        infra_vision: 2,
        exp_factor_base: 110,
        classes_bit_field: 0x3F,
    },
    Race {
        name: "Elf",
        str_adjustment: -1,
        int_adjustment: 2,
        wis_adjustment: 1,
        dex_adjustment: 1,
        con_adjustment: -2,
        chr_adjustment: 1,
        base_age: 75,
        max_age: 75,
        male_height_base: 60,
        male_height_mod: 4,
        male_weight_base: 100,
        male_weight_mod: 6,
        female_height_base: 54,
        female_height_mod: 4,
        female_weight_base: 80,
        female_weight_mod: 6,
        disarm_chance_base: 5,
        search_chance_base: 8,
        stealth: 1,
        fos: -2,
        base_to_hit: -5,
        base_to_hit_bows: 15,
        saving_throw_base: 6,
        hit_points_base: 8,
        infra_vision: 3,
        exp_factor_base: 120,
        classes_bit_field: 0x1F,
    },
    Race {
        name: "Halfling",
        str_adjustment: -2,
        int_adjustment: 2,
        wis_adjustment: 1,
        dex_adjustment: 3,
        con_adjustment: 1,
        chr_adjustment: 1,
        base_age: 21,
        max_age: 12,
        male_height_base: 36,
        male_height_mod: 3,
        male_weight_base: 60,
        male_weight_mod: 3,
        female_height_base: 33,
        female_height_mod: 3,
        female_weight_base: 50,
        female_weight_mod: 3,
        disarm_chance_base: 15,
        search_chance_base: 12,
        stealth: 4,
        fos: -5,
        base_to_hit: -10,
        base_to_hit_bows: 20,
        saving_throw_base: 18,
        hit_points_base: 6,
        infra_vision: 4,
        exp_factor_base: 110,
        classes_bit_field: 0x0B,
    },
    Race {
        name: "Gnome",
        str_adjustment: -1,
        int_adjustment: 2,
        wis_adjustment: 0,
        dex_adjustment: 2,
        con_adjustment: 1,
        chr_adjustment: -2,
        base_age: 50,
        max_age: 40,
        male_height_base: 42,
        male_height_mod: 3,
        male_weight_base: 90,
        male_weight_mod: 6,
        female_height_base: 39,
        female_height_mod: 3,
        female_weight_base: 75,
        female_weight_mod: 3,
        disarm_chance_base: 10,
        search_chance_base: 6,
        stealth: 3,
        fos: -3,
        base_to_hit: -8,
        base_to_hit_bows: 12,
        saving_throw_base: 12,
        hit_points_base: 7,
        infra_vision: 4,
        exp_factor_base: 125,
        classes_bit_field: 0x0F,
    },
    Race {
        name: "Dwarf",
        str_adjustment: 2,
        int_adjustment: -3,
        wis_adjustment: 1,
        dex_adjustment: -2,
        con_adjustment: 2,
        chr_adjustment: -3,
        base_age: 35,
        max_age: 15,
        male_height_base: 48,
        male_height_mod: 3,
        male_weight_base: 150,
        male_weight_mod: 10,
        female_height_base: 46,
        female_height_mod: 3,
        female_weight_base: 120,
        female_weight_mod: 10,
        disarm_chance_base: 2,
        search_chance_base: 7,
        stealth: -1,
        fos: 0,
        base_to_hit: 15,
        base_to_hit_bows: 0,
        saving_throw_base: 9,
        hit_points_base: 9,
        infra_vision: 5,
        exp_factor_base: 120,
        classes_bit_field: 0x05,
    },
    Race {
        name: "Half-Orc",
        str_adjustment: 2,
        int_adjustment: -1,
        wis_adjustment: 0,
        dex_adjustment: 0,
        con_adjustment: 1,
        chr_adjustment: -4,
        base_age: 11,
        max_age: 4,
        male_height_base: 66,
        male_height_mod: 1,
        male_weight_base: 150,
        male_weight_mod: 5,
        female_height_base: 62,
        female_height_mod: 1,
        female_weight_base: 120,
        female_weight_mod: 5,
        disarm_chance_base: -3,
        search_chance_base: 0,
        stealth: -1,
        fos: 3,
        base_to_hit: 12,
        base_to_hit_bows: -5,
        saving_throw_base: -3,
        hit_points_base: 10,
        infra_vision: 3,
        exp_factor_base: 110,
        classes_bit_field: 0x0D,
    },
    Race {
        name: "Half-Troll",
        str_adjustment: 4,
        int_adjustment: -4,
        wis_adjustment: -2,
        dex_adjustment: -4,
        con_adjustment: 3,
        chr_adjustment: -6,
        base_age: 20,
        max_age: 10,
        male_height_base: 96,
        male_height_mod: 10,
        male_weight_base: 255,
        male_weight_mod: 50,
        female_height_base: 84,
        female_height_mod: 8,
        female_weight_base: 225,
        female_weight_mod: 40,
        disarm_chance_base: -5,
        search_chance_base: -1,
        stealth: -2,
        fos: 5,
        base_to_hit: 20,
        base_to_hit_bows: -10,
        saving_throw_base: -8,
        hit_points_base: 12,
        infra_vision: 3,
        exp_factor_base: 120,
        classes_bit_field: 0x05,
    },
];

// Background information
pub static CHARACTER_BACKGROUNDS: [Background; PLAYER_MAX_BACKGROUNDS] = [
    Background { info: "You are the illegitimate and unacknowledged child ", roll: 10, chart: 1, next: 2, bonus: 25 },
    Background { info: "You are the illegitimate but acknowledged child ", roll: 20, chart: 1, next: 2, bonus: 35 },
    Background { info: "You are one of several children ", roll: 95, chart: 1, next: 2, bonus: 45 },
    Background { info: "You are the first child ", roll: 100, chart: 1, next: 2, bonus: 50 },
    Background { info: "of a Serf.  ", roll: 40, chart: 2, next: 3, bonus: 65 },
    Background { info: "of a Yeoman.  ", roll: 65, chart: 2, next: 3, bonus: 80 },
    Background { info: "of a Townsman.  ", roll: 80, chart: 2, next: 3, bonus: 90 },
    Background { info: "of a Guildsman.  ", roll: 90, chart: 2, next: 3, bonus: 105 },
    Background { info: "of a Landed Knight.  ", roll: 96, chart: 2, next: 3, bonus: 120 },
    Background { info: "of a Titled Noble.  ", roll: 99, chart: 2, next: 3, bonus: 130 },
    Background { info: "of a Royal Blood Line.  ", roll: 100, chart: 2, next: 3, bonus: 140 },
    Background { info: "You are the black sheep of the family.  ", roll: 20, chart: 3, next: 50, bonus: 20 },
    Background { info: "You are a credit to the family.  ", roll: 80, chart: 3, next: 50, bonus: 55 },
    Background { info: "You are a well liked child.  ", roll: 100, chart: 3, next: 50, bonus: 60 },
    Background { info: "Your mother was a Green-Elf.  ", roll: 40, chart: 4, next: 1, bonus: 50 },
    Background { info: "Your father was a Green-Elf.  ", roll: 75, chart: 4, next: 1, bonus: 55 },
    Background { info: "Your mother was a Grey-Elf.  ", roll: 90, chart: 4, next: 1, bonus: 55 },
    Background { info: "Your father was a Grey-Elf.  ", roll: 95, chart: 4, next: 1, bonus: 60 },
    Background { info: "Your mother was a High-Elf.  ", roll: 98, chart: 4, next: 1, bonus: 65 },
    Background { info: "Your father was a High-Elf.  ", roll: 100, chart: 4, next: 1, bonus: 70 },
    Background { info: "You are one of several children ", roll: 60, chart: 7, next: 8, bonus: 50 },
    Background { info: "You are the only child ", roll: 100, chart: 7, next: 8, bonus: 55 },
    Background { info: "of a Green-Elf ", roll: 75, chart: 8, next: 9, bonus: 50 },
    Background { info: "of a Grey-Elf ", roll: 95, chart: 8, next: 9, bonus: 55 },
    Background { info: "of a High-Elf ", roll: 100, chart: 8, next: 9, bonus: 60 },
    Background { info: "Ranger.  ", roll: 40, chart: 9, next: 54, bonus: 80 },
    Background { info: "Archer.  ", roll: 70, chart: 9, next: 54, bonus: 90 },
    Background { info: "Warrior.  ", roll: 87, chart: 9, next: 54, bonus: 110 },
    Background { info: "Mage.  ", roll: 95, chart: 9, next: 54, bonus: 125 },
    Background { info: "Prince.  ", roll: 99, chart: 9, next: 54, bonus: 140 },
    Background { info: "King.  ", roll: 100, chart: 9, next: 54, bonus: 145 },
    Background { info: "You are one of several children of a Halfling ", roll: 85, chart: 10, next: 11, bonus: 45 },
    Background { info: "You are the only child of a Halfling ", roll: 100, chart: 10, next: 11, bonus: 55 },
    Background { info: "Bum.  ", roll: 20, chart: 11, next: 3, bonus: 55 },
    Background { info: "Tavern Owner.  ", roll: 30, chart: 11, next: 3, bonus: 80 },
    Background { info: "Miller.  ", roll: 40, chart: 11, next: 3, bonus: 90 },
    Background { info: "Home Owner.  ", roll: 50, chart: 11, next: 3, bonus: 100 },
    Background { info: "Burglar.  ", roll: 80, chart: 11, next: 3, bonus: 110 },
    Background { info: "Warrior.  ", roll: 95, chart: 11, next: 3, bonus: 115 },
    Background { info: "Mage.  ", roll: 99, chart: 11, next: 3, bonus: 125 },
    Background { info: "Clan Elder.  ", roll: 100, chart: 11, next: 3, bonus: 140 },
    Background { info: "You are one of several children of a Gnome ", roll: 85, chart: 13, next: 14, bonus: 45 },
    Background { info: "You are the only child of a Gnome ", roll: 100, chart: 13, next: 14, bonus: 55 },
    Background { info: "Beggar.  ", roll: 20, chart: 14, next: 3, bonus: 55 },
    Background { info: "Braggart.  ", roll: 50, chart: 14, next: 3, bonus: 70 },
    Background { info: "Prankster.  ", roll: 75, chart: 14, next: 3, bonus: 85 },
    Background { info: "Warrior.  ", roll: 95, chart: 14, next: 3, bonus: 100 },
    Background { info: "Mage.  ", roll: 100, chart: 14, next: 3, bonus: 125 },
    Background { info: "You are one of two children of a Dwarven ", roll: 25, chart: 16, next: 17, bonus: 40 },
    Background { info: "You are the only child of a Dwarven ", roll: 100, chart: 16, next: 17, bonus: 50 },
    Background { info: "Thief.  ", roll: 10, chart: 17, next: 18, bonus: 60 },
    Background { info: "Prison Guard.  ", roll: 25, chart: 17, next: 18, bonus: 75 },
    Background { info: "Miner.  ", roll: 75, chart: 17, next: 18, bonus: 90 },
    Background { info: "Warrior.  ", roll: 90, chart: 17, next: 18, bonus: 110 },
    Background { info: "Priest.  ", roll: 99, chart: 17, next: 18, bonus: 130 },
    Background { info: "King.  ", roll: 100, chart: 17, next: 18, bonus: 150 },
    Background { info: "You are the black sheep of the family.  ", roll: 15, chart: 18, next: 57, bonus: 10 },
    Background { info: "You are a credit to the family.  ", roll: 85, chart: 18, next: 57, bonus: 50 },
    Background { info: "You are a well liked child.  ", roll: 100, chart: 18, next: 57, bonus: 55 },
    Background { info: "Your mother was an Orc, but it is unacknowledged.  ", roll: 25, chart: 19, next: 20, bonus: 25 },
    Background { info: "Your father was an Orc, but it is unacknowledged.  ", roll: 100, chart: 19, next: 20, bonus: 25 },
    Background { info: "You are the adopted child ", roll: 100, chart: 20, next: 2, bonus: 50 },
    Background { info: "Your mother was a Cave-Troll ", roll: 30, chart: 22, next: 23, bonus: 20 },
    Background { info: "Your father was a Cave-Troll ", roll: 60, chart: 22, next: 23, bonus: 25 },
    Background { info: "Your mother was a Hill-Troll ", roll: 75, chart: 22, next: 23, bonus: 30 },
    Background { info: "Your father was a Hill-Troll ", roll: 90, chart: 22, next: 23, bonus: 35 },
    Background { info: "Your mother was a Water-Troll ", roll: 95, chart: 22, next: 23, bonus: 40 },
    Background { info: "Your father was a Water-Troll ", roll: 100, chart: 22, next: 23, bonus: 45 },
    Background { info: "Cook.  ", roll: 5, chart: 23, next: 62, bonus: 60 },
    Background { info: "Warrior.  ", roll: 95, chart: 23, next: 62, bonus: 55 },
    Background { info: "Shaman.  ", roll: 99, chart: 23, next: 62, bonus: 65 },
    Background { info: "Clan Chief.  ", roll: 100, chart: 23, next: 62, bonus: 80 },
    Background { info: "You have dark brown eyes, ", roll: 20, chart: 50, next: 51, bonus: 50 },
    Background { info: "You have brown eyes, ", roll: 60, chart: 50, next: 51, bonus: 50 },
    Background { info: "You have hazel eyes, ", roll: 70, chart: 50, next: 51, bonus: 50 },
    Background { info: "You have green eyes, ", roll: 80, chart: 50, next: 51, bonus: 50 },
    Background { info: "You have blue eyes, ", roll: 90, chart: 50, next: 51, bonus: 50 },
    Background { info: "You have blue-gray eyes, ", roll: 100, chart: 50, next: 51, bonus: 50 },
    Background { info: "straight ", roll: 70, chart: 51, next: 52, bonus: 50 },
    Background { info: "wavy ", roll: 90, chart: 51, next: 52, bonus: 50 },
    Background { info: "curly ", roll: 100, chart: 51, next: 52, bonus: 50 },
    Background { info: "black hair, ", roll: 30, chart: 52, next: 53, bonus: 50 },
    Background { info: "brown hair, ", roll: 70, chart: 52, next: 53, bonus: 50 },
    Background { info: "auburn hair, ", roll: 80, chart: 52, next: 53, bonus: 50 },
    Background { info: "red hair, ", roll: 90, chart: 52, next: 53, bonus: 50 },
    Background { info: "blond hair, ", roll: 100, chart: 52, next: 53, bonus: 50 },
    Background { info: "and a very dark complexion.", roll: 10, chart: 53, next: 0, bonus: 50 },
    Background { info: "and a dark complexion.", roll: 30, chart: 53, next: 0, bonus: 50 },
    Background { info: "and an average complexion.", roll: 80, chart: 53, next: 0, bonus: 50 },
    Background { info: "and a fair complexion.", roll: 90, chart: 53, next: 0, bonus: 50 },
    Background { info: "and a very fair complexion.", roll: 100, chart: 53, next: 0, bonus: 50 },
    Background { info: "You have light grey eyes, ", roll: 85, chart: 54, next: 55, bonus: 50 },
    Background { info: "You have light blue eyes, ", roll: 95, chart: 54, next: 55, bonus: 50 },
    Background { info: "You have light green eyes, ", roll: 100, chart: 54, next: 55, bonus: 50 },
    Background { info: "straight ", roll: 75, chart: 55, next: 56, bonus: 50 },
    Background { info: "wavy ", roll: 100, chart: 55, next: 56, bonus: 50 },
    Background { info: "black hair, and a fair complexion.", roll: 75, chart: 56, next: 0, bonus: 50 },
    Background { info: "brown hair, and a fair complexion.", roll: 85, chart: 56, next: 0, bonus: 50 },
    Background { info: "blond hair, and a fair complexion.", roll: 95, chart: 56, next: 0, bonus: 50 },
    Background { info: "silver hair, and a fair complexion.", roll: 100, chart: 56, next: 0, bonus: 50 },
    Background { info: "You have dark brown eyes, ", roll: 99, chart: 57, next: 58, bonus: 50 },
    Background { info: "You have glowing red eyes, ", roll: 100, chart: 57, next: 58, bonus: 60 },
    Background { info: "straight ", roll: 90, chart: 58, next: 59, bonus: 50 },
    Background { info: "wavy ", roll: 100, chart: 58, next: 59, bonus: 50 },
    Background { info: "black hair, ", roll: 75, chart: 59, next: 60, bonus: 50 },
    Background { info: "brown hair, ", roll: 100, chart: 59, next: 60, bonus: 50 },
    Background { info: "a one foot beard, ", roll: 25, chart: 60, next: 61, bonus: 50 },
    Background { info: "a two foot beard, ", roll: 60, chart: 60, next: 61, bonus: 51 },
    Background { info: "a three foot beard, ", roll: 90, chart: 60, next: 61, bonus: 53 },
    Background { info: "a four foot beard, ", roll: 100, chart: 60, next: 61, bonus: 55 },
    Background { info: "and a dark complexion.", roll: 100, chart: 61, next: 0, bonus: 50 },
    Background { info: "You have slime green eyes, ", roll: 60, chart: 62, next: 63, bonus: 50 },
    Background { info: "You have puke yellow eyes, ", roll: 85, chart: 62, next: 63, bonus: 50 },
    Background { info: "You have blue-bloodshot eyes, ", roll: 99, chart: 62, next: 63, bonus: 50 },
    Background { info: "You have glowing red eyes, ", roll: 100, chart: 62, next: 63, bonus: 55 },
    Background { info: "dirty ", roll: 33, chart: 63, next: 64, bonus: 50 },
    Background { info: "mangy ", roll: 66, chart: 63, next: 64, bonus: 50 },
    Background { info: "oily ", roll: 100, chart: 63, next: 64, bonus: 50 },
    Background { info: "sea-weed green hair, ", roll: 33, chart: 64, next: 65, bonus: 50 },
    Background { info: "bright red hair, ", roll: 66, chart: 64, next: 65, bonus: 50 },
    Background { info: "dark purple hair, ", roll: 100, chart: 64, next: 65, bonus: 50 },
    Background { info: "and green ", roll: 25, chart: 65, next: 66, bonus: 50 },
    Background { info: "and blue ", roll: 50, chart: 65, next: 66, bonus: 50 },
    Background { info: "and white ", roll: 75, chart: 65, next: 66, bonus: 50 },
    Background { info: "and black ", roll: 100, chart: 65, next: 66, bonus: 50 },
    Background { info: "ulcerous skin.", roll: 33, chart: 66, next: 0, bonus: 50 },
    Background { info: "scabby skin.", roll: 66, chart: 66, next: 0, bonus: 50 },
    Background { info: "leprous skin.", roll: 100, chart: 66, next: 0, bonus: 50 },
];

// Classes.
pub static CLASSES: [Class; PLAYER_MAX_CLASSES] = [
    Class { title: "Warrior", hit_points: 9, disarm_traps: 25, searching: 14, stealth: 1, fos: 38, base_to_hit: 70, base_to_hit_with_bows: 55, saving_throw: 18, strength: 5, intelligence: -2, wisdom: -2, dexterity: 2, constitution: 2, charisma: -1, class_to_use_mage_spells: config::spells::SPELL_TYPE_NONE, experience_factor: 0, min_level_for_spell_casting: 0 },
    Class { title: "Mage", hit_points: 0, disarm_traps: 30, searching: 16, stealth: 2, fos: 20, base_to_hit: 34, base_to_hit_with_bows: 20, saving_throw: 36, strength: -5, intelligence: 3, wisdom: 0, dexterity: 1, constitution: -2, charisma: 1, class_to_use_mage_spells: config::spells::SPELL_TYPE_MAGE, experience_factor: 30, min_level_for_spell_casting: 1 },
    Class { title: "Priest", hit_points: 2, disarm_traps: 25, searching: 16, stealth: 2, fos: 32, base_to_hit: 48, base_to_hit_with_bows: 35, saving_throw: 30, strength: -3, intelligence: -3, wisdom: 3, dexterity: -1, constitution: 0, charisma: 2, class_to_use_mage_spells: config::spells::SPELL_TYPE_PRIEST, experience_factor: 20, min_level_for_spell_casting: 1 },
    Class { title: "Rogue", hit_points: 6, disarm_traps: 45, searching: 32, stealth: 5, fos: 16, base_to_hit: 60, base_to_hit_with_bows: 66, saving_throw: 30, strength: 2, intelligence: 1, wisdom: -2, dexterity: 3, constitution: 1, charisma: -1, class_to_use_mage_spells: config::spells::SPELL_TYPE_MAGE, experience_factor: 0, min_level_for_spell_casting: 5 },
    Class { title: "Ranger", hit_points: 4, disarm_traps: 30, searching: 24, stealth: 3, fos: 24, base_to_hit: 56, base_to_hit_with_bows: 72, saving_throw: 30, strength: 2, intelligence: 2, wisdom: 0, dexterity: 1, constitution: 1, charisma: 1, class_to_use_mage_spells: config::spells::SPELL_TYPE_MAGE, experience_factor: 40, min_level_for_spell_casting: 3 },
    Class { title: "Paladin", hit_points: 6, disarm_traps: 20, searching: 12, stealth: 1, fos: 38, base_to_hit: 68, base_to_hit_with_bows: 40, saving_throw: 24, strength: 3, intelligence: -3, wisdom: 1, dexterity: 0, constitution: 2, charisma: 2, class_to_use_mage_spells: config::spells::SPELL_TYPE_PRIEST, experience_factor: 35, min_level_for_spell_casting: 1 },
];

// CLASS_MISC_HIT is identical to CLASS_SAVE, which takes advantage of
// the fact that the save values are independent of the class.
// Columns: bth, bth_with_bows, device, disarm, save/misc hit
pub static CLASS_LEVEL_ADJ: [[i16; CLASS_MAX_LEVEL_ADJUST]; PLAYER_MAX_CLASSES] = [
    [4, 4, 2, 2, 3], // Warrior
    [2, 2, 4, 3, 3], // Mage
    [2, 2, 4, 3, 3], // Priests
    [3, 4, 3, 4, 3], // Rogues
    [3, 4, 3, 3, 3], // Rangers
    [3, 3, 3, 2, 3], // Paladins
];

// Warriors don't have spells, so there is no entry for them.
// Note that this means you must always subtract one from the
// py.misc.class_id before indexing into magic_spells[].
pub static MAGIC_SPELLS: [[Spell; 31]; PLAYER_MAX_CLASSES - 1] = [
    // Mage
    [
        Spell { level_required: 1, mana_required: 1, failure_chance: 22, exp_gain_for_learning: 1 },
        Spell { level_required: 1, mana_required: 1, failure_chance: 23, exp_gain_for_learning: 1 },
        Spell { level_required: 1, mana_required: 2, failure_chance: 24, exp_gain_for_learning: 1 },
        Spell { level_required: 1, mana_required: 2, failure_chance: 26, exp_gain_for_learning: 1 },
        Spell { level_required: 3, mana_required: 3, failure_chance: 25, exp_gain_for_learning: 2 },
        Spell { level_required: 3, mana_required: 3, failure_chance: 25, exp_gain_for_learning: 1 },
        Spell { level_required: 3, mana_required: 3, failure_chance: 27, exp_gain_for_learning: 2 },
        Spell { level_required: 3, mana_required: 4, failure_chance: 30, exp_gain_for_learning: 1 },
        Spell { level_required: 5, mana_required: 4, failure_chance: 30, exp_gain_for_learning: 6 },
        Spell { level_required: 5, mana_required: 5, failure_chance: 30, exp_gain_for_learning: 8 },
        Spell { level_required: 5, mana_required: 5, failure_chance: 30, exp_gain_for_learning: 5 },
        Spell { level_required: 5, mana_required: 5, failure_chance: 35, exp_gain_for_learning: 6 },
        Spell { level_required: 7, mana_required: 6, failure_chance: 35, exp_gain_for_learning: 9 },
        Spell { level_required: 7, mana_required: 6, failure_chance: 50, exp_gain_for_learning: 10 },
        Spell { level_required: 7, mana_required: 6, failure_chance: 40, exp_gain_for_learning: 12 },
        Spell { level_required: 9, mana_required: 7, failure_chance: 44, exp_gain_for_learning: 19 },
        Spell { level_required: 9, mana_required: 7, failure_chance: 45, exp_gain_for_learning: 19 },
        Spell { level_required: 9, mana_required: 7, failure_chance: 75, exp_gain_for_learning: 22 },
        Spell { level_required: 9, mana_required: 7, failure_chance: 45, exp_gain_for_learning: 19 },
        Spell { level_required: 11, mana_required: 7, failure_chance: 45, exp_gain_for_learning: 25 },
        Spell { level_required: 11, mana_required: 7, failure_chance: 99, exp_gain_for_learning: 19 },
        Spell { level_required: 13, mana_required: 7, failure_chance: 50, exp_gain_for_learning: 22 },
        Spell { level_required: 15, mana_required: 9, failure_chance: 50, exp_gain_for_learning: 25 },
        Spell { level_required: 17, mana_required: 9, failure_chance: 50, exp_gain_for_learning: 31 },
        Spell { level_required: 19, mana_required: 12, failure_chance: 55, exp_gain_for_learning: 38 },
        Spell { level_required: 21, mana_required: 12, failure_chance: 90, exp_gain_for_learning: 44 },
        Spell { level_required: 23, mana_required: 12, failure_chance: 60, exp_gain_for_learning: 50 },
        Spell { level_required: 25, mana_required: 12, failure_chance: 65, exp_gain_for_learning: 63 },
        Spell { level_required: 29, mana_required: 18, failure_chance: 65, exp_gain_for_learning: 88 },
        Spell { level_required: 33, mana_required: 21, failure_chance: 80, exp_gain_for_learning: 125 },
        Spell { level_required: 37, mana_required: 25, failure_chance: 95, exp_gain_for_learning: 200 },
    ],
    // Priest
    [
        Spell { level_required: 1, mana_required: 1, failure_chance: 10, exp_gain_for_learning: 1 },
        Spell { level_required: 1, mana_required: 2, failure_chance: 15, exp_gain_for_learning: 1 },
        Spell { level_required: 1, mana_required: 2, failure_chance: 20, exp_gain_for_learning: 1 },
        Spell { level_required: 1, mana_required: 2, failure_chance: 25, exp_gain_for_learning: 1 },
        Spell { level_required: 3, mana_required: 2, failure_chance: 25, exp_gain_for_learning: 1 },
        Spell { level_required: 3, mana_required: 3, failure_chance: 27, exp_gain_for_learning: 2 },
        Spell { level_required: 3, mana_required: 3, failure_chance: 27, exp_gain_for_learning: 2 },
        Spell { level_required: 3, mana_required: 3, failure_chance: 28, exp_gain_for_learning: 3 },
        Spell { level_required: 5, mana_required: 4, failure_chance: 29, exp_gain_for_learning: 4 },
        Spell { level_required: 5, mana_required: 4, failure_chance: 30, exp_gain_for_learning: 5 },
        Spell { level_required: 5, mana_required: 4, failure_chance: 32, exp_gain_for_learning: 5 },
        Spell { level_required: 5, mana_required: 5, failure_chance: 34, exp_gain_for_learning: 5 },
        Spell { level_required: 7, mana_required: 5, failure_chance: 36, exp_gain_for_learning: 6 },
        Spell { level_required: 7, mana_required: 5, failure_chance: 38, exp_gain_for_learning: 7 },
        Spell { level_required: 7, mana_required: 6, failure_chance: 38, exp_gain_for_learning: 9 },
        Spell { level_required: 7, mana_required: 7, failure_chance: 38, exp_gain_for_learning: 9 },
        Spell { level_required: 9, mana_required: 6, failure_chance: 38, exp_gain_for_learning: 10 },
        Spell { level_required: 9, mana_required: 7, failure_chance: 38, exp_gain_for_learning: 10 },
        Spell { level_required: 9, mana_required: 7, failure_chance: 40, exp_gain_for_learning: 10 },
        Spell { level_required: 11, mana_required: 8, failure_chance: 42, exp_gain_for_learning: 10 },
        Spell { level_required: 11, mana_required: 8, failure_chance: 42, exp_gain_for_learning: 12 },
        Spell { level_required: 11, mana_required: 9, failure_chance: 55, exp_gain_for_learning: 15 },
        Spell { level_required: 13, mana_required: 10, failure_chance: 45, exp_gain_for_learning: 15 },
        Spell { level_required: 13, mana_required: 11, failure_chance: 45, exp_gain_for_learning: 16 },
        Spell { level_required: 15, mana_required: 12, failure_chance: 50, exp_gain_for_learning: 20 },
        Spell { level_required: 15, mana_required: 14, failure_chance: 50, exp_gain_for_learning: 22 },
        Spell { level_required: 17, mana_required: 14, failure_chance: 55, exp_gain_for_learning: 32 },
        Spell { level_required: 21, mana_required: 16, failure_chance: 60, exp_gain_for_learning: 38 },
        Spell { level_required: 25, mana_required: 20, failure_chance: 70, exp_gain_for_learning: 75 },
        Spell { level_required: 33, mana_required: 24, failure_chance: 90, exp_gain_for_learning: 125 },
        Spell { level_required: 39, mana_required: 32, failure_chance: 80, exp_gain_for_learning: 200 },
    ],
    // Rogue
    [
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 5, mana_required: 1, failure_chance: 50, exp_gain_for_learning: 1 },
        Spell { level_required: 7, mana_required: 2, failure_chance: 55, exp_gain_for_learning: 1 },
        Spell { level_required: 9, mana_required: 3, failure_chance: 60, exp_gain_for_learning: 2 },
        Spell { level_required: 11, mana_required: 4, failure_chance: 65, exp_gain_for_learning: 2 },
        Spell { level_required: 13, mana_required: 5, failure_chance: 70, exp_gain_for_learning: 3 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 15, mana_required: 6, failure_chance: 75, exp_gain_for_learning: 3 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 17, mana_required: 7, failure_chance: 80, exp_gain_for_learning: 4 },
        Spell { level_required: 19, mana_required: 8, failure_chance: 85, exp_gain_for_learning: 5 },
        Spell { level_required: 21, mana_required: 9, failure_chance: 90, exp_gain_for_learning: 6 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 23, mana_required: 10, failure_chance: 95, exp_gain_for_learning: 7 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 25, mana_required: 12, failure_chance: 95, exp_gain_for_learning: 9 },
        Spell { level_required: 27, mana_required: 15, failure_chance: 99, exp_gain_for_learning: 11 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 29, mana_required: 18, failure_chance: 99, exp_gain_for_learning: 19 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
    ],
    // Ranger
    [
        Spell { level_required: 3, mana_required: 1, failure_chance: 30, exp_gain_for_learning: 1 },
        Spell { level_required: 3, mana_required: 2, failure_chance: 35, exp_gain_for_learning: 2 },
        Spell { level_required: 3, mana_required: 2, failure_chance: 35, exp_gain_for_learning: 2 },
        Spell { level_required: 5, mana_required: 3, failure_chance: 35, exp_gain_for_learning: 2 },
        Spell { level_required: 5, mana_required: 3, failure_chance: 40, exp_gain_for_learning: 2 },
        Spell { level_required: 5, mana_required: 4, failure_chance: 45, exp_gain_for_learning: 3 },
        Spell { level_required: 7, mana_required: 5, failure_chance: 40, exp_gain_for_learning: 6 },
        Spell { level_required: 7, mana_required: 6, failure_chance: 40, exp_gain_for_learning: 5 },
        Spell { level_required: 9, mana_required: 7, failure_chance: 40, exp_gain_for_learning: 7 },
        Spell { level_required: 9, mana_required: 8, failure_chance: 45, exp_gain_for_learning: 8 },
        Spell { level_required: 11, mana_required: 8, failure_chance: 40, exp_gain_for_learning: 10 },
        Spell { level_required: 11, mana_required: 9, failure_chance: 45, exp_gain_for_learning: 10 },
        Spell { level_required: 13, mana_required: 10, failure_chance: 45, exp_gain_for_learning: 12 },
        Spell { level_required: 13, mana_required: 11, failure_chance: 55, exp_gain_for_learning: 13 },
        Spell { level_required: 15, mana_required: 12, failure_chance: 50, exp_gain_for_learning: 15 },
        Spell { level_required: 15, mana_required: 13, failure_chance: 50, exp_gain_for_learning: 15 },
        Spell { level_required: 17, mana_required: 17, failure_chance: 55, exp_gain_for_learning: 15 },
        Spell { level_required: 17, mana_required: 17, failure_chance: 90, exp_gain_for_learning: 17 },
        Spell { level_required: 21, mana_required: 17, failure_chance: 55, exp_gain_for_learning: 17 },
        Spell { level_required: 21, mana_required: 19, failure_chance: 60, exp_gain_for_learning: 18 },
        Spell { level_required: 23, mana_required: 25, failure_chance: 95, exp_gain_for_learning: 20 },
        Spell { level_required: 23, mana_required: 20, failure_chance: 60, exp_gain_for_learning: 20 },
        Spell { level_required: 25, mana_required: 20, failure_chance: 60, exp_gain_for_learning: 20 },
        Spell { level_required: 25, mana_required: 21, failure_chance: 65, exp_gain_for_learning: 20 },
        Spell { level_required: 27, mana_required: 21, failure_chance: 65, exp_gain_for_learning: 22 },
        Spell { level_required: 29, mana_required: 23, failure_chance: 95, exp_gain_for_learning: 23 },
        Spell { level_required: 31, mana_required: 25, failure_chance: 70, exp_gain_for_learning: 25 },
        Spell { level_required: 33, mana_required: 25, failure_chance: 75, exp_gain_for_learning: 38 },
        Spell { level_required: 35, mana_required: 25, failure_chance: 80, exp_gain_for_learning: 50 },
        Spell { level_required: 37, mana_required: 30, failure_chance: 95, exp_gain_for_learning: 100 },
        Spell { level_required: 99, mana_required: 99, failure_chance: 0, exp_gain_for_learning: 0 },
    ],
    // Paladin
    [
        Spell { level_required: 1, mana_required: 1, failure_chance: 30, exp_gain_for_learning: 1 },
        Spell { level_required: 2, mana_required: 2, failure_chance: 35, exp_gain_for_learning: 2 },
        Spell { level_required: 3, mana_required: 3, failure_chance: 35, exp_gain_for_learning: 3 },
        Spell { level_required: 5, mana_required: 3, failure_chance: 35, exp_gain_for_learning: 5 },
        Spell { level_required: 5, mana_required: 4, failure_chance: 35, exp_gain_for_learning: 5 },
        Spell { level_required: 7, mana_required: 5, failure_chance: 40, exp_gain_for_learning: 6 },
        Spell { level_required: 7, mana_required: 5, failure_chance: 40, exp_gain_for_learning: 6 },
        Spell { level_required: 9, mana_required: 7, failure_chance: 40, exp_gain_for_learning: 7 },
        Spell { level_required: 9, mana_required: 7, failure_chance: 40, exp_gain_for_learning: 8 },
        Spell { level_required: 9, mana_required: 8, failure_chance: 40, exp_gain_for_learning: 8 },
        Spell { level_required: 11, mana_required: 9, failure_chance: 40, exp_gain_for_learning: 10 },
        Spell { level_required: 11, mana_required: 10, failure_chance: 45, exp_gain_for_learning: 10 },
        Spell { level_required: 11, mana_required: 10, failure_chance: 45, exp_gain_for_learning: 10 },
        Spell { level_required: 13, mana_required: 10, failure_chance: 45, exp_gain_for_learning: 12 },
        Spell { level_required: 13, mana_required: 11, failure_chance: 45, exp_gain_for_learning: 13 },
        Spell { level_required: 15, mana_required: 13, failure_chance: 45, exp_gain_for_learning: 15 },
        Spell { level_required: 15, mana_required: 15, failure_chance: 50, exp_gain_for_learning: 15 },
        Spell { level_required: 17, mana_required: 15, failure_chance: 50, exp_gain_for_learning: 17 },
        Spell { level_required: 17, mana_required: 15, failure_chance: 50, exp_gain_for_learning: 18 },
        Spell { level_required: 19, mana_required: 15, failure_chance: 50, exp_gain_for_learning: 19 },
        Spell { level_required: 19, mana_required: 15, failure_chance: 50, exp_gain_for_learning: 19 },
        Spell { level_required: 21, mana_required: 17, failure_chance: 50, exp_gain_for_learning: 20 },
        Spell { level_required: 23, mana_required: 17, failure_chance: 50, exp_gain_for_learning: 20 },
        Spell { level_required: 25, mana_required: 20, failure_chance: 50, exp_gain_for_learning: 20 },
        Spell { level_required: 27, mana_required: 21, failure_chance: 50, exp_gain_for_learning: 22 },
        Spell { level_required: 29, mana_required: 22, failure_chance: 50, exp_gain_for_learning: 24 },
        Spell { level_required: 31, mana_required: 24, failure_chance: 60, exp_gain_for_learning: 25 },
        Spell { level_required: 33, mana_required: 28, failure_chance: 60, exp_gain_for_learning: 31 },
        Spell { level_required: 35, mana_required: 32, failure_chance: 70, exp_gain_for_learning: 38 },
        Spell { level_required: 37, mana_required: 36, failure_chance: 90, exp_gain_for_learning: 50 },
        Spell { level_required: 39, mana_required: 38, failure_chance: 90, exp_gain_for_learning: 100 },
    ],
];

pub static SPELL_NAMES: [&str; 62] = [
    // Mage Spells
    "Magic Missile",
    "Detect Monsters",
    "Phase Door",
    "Light Area",
    "Cure Light Wounds",
    "Find Hidden Traps/Doors",
    "Stinking Cloud",
    "Confusion",
    "Lightning Bolt",
    "Trap/Door Destruction",
    "Sleep I",
    "Cure Poison",
    "Teleport Self",
    "Remove Curse",
    "Frost Bolt",
    "Turn Stone to Mud",
    "Create Food",
    "Recharge Item I",
    "Sleep II",
    "Polymorph Other",
    "Identify",
    "Sleep III",
    "Fire Bolt",
    "Slow Monster",
    "Frost Ball",
    "Recharge Item II",
    "Teleport Other",
    "Haste Self",
    "Fire Ball",
    "Word of Destruction",
    "Genocide",
    // Priest Spells, start at index 31
    "Detect Evil",
    "Cure Light Wounds",
    "Bless",
    "Remove Fear",
    "Call Light",
    "Find Traps",
    "Detect Doors/Stairs",
    "Slow Poison",
    "Blind Creature",
    "Portal",
    "Cure Medium Wounds",
    "Chant",
    "Sanctuary",
    "Create Food",
    "Remove Curse",
    "Resist Heat and Cold",
    "Neutralize Poison",
    "Orb of Draining",
    "Cure Serious Wounds",
    "Sense Invisible",
    "Protection from Evil",
    "Earthquake",
    "Sense Surroundings",
    "Cure Critical Wounds",
    "Turn Undead",
    "Prayer",
    "Dispel Undead",
    "Heal",
    "Dispel Evil",
    "Glyph of Warding",
    "Holy Word",
];

// Each type of character starts out with a few provisions.
//
// Note that the entries refer to elements of the game_objects[] array.
//      344 = Food Ration
//      365 = Wooden Torch
//      123 = Cloak
//      318 = Beginners-Magick
//      103 = Soft Leather Armor
//       30 = Stiletto
//      322 = Beginners Handbook
pub static CLASS_BASE_PROVISIONS: [[u16; 5]; PLAYER_MAX_CLASSES] = [
    [344, 365, 123, 30, 103], // Warrior
    [344, 365, 123, 30, 318], // Mage
    [344, 365, 123, 30, 322], // Priests
    [344, 365, 123, 30, 318], // Rogues
    [344, 365, 123, 30, 318], // Rangers
    [344, 365, 123, 30, 322], // Paladins
];
